// packages/react-table/src/module/table/table-header-cell.tsx
import type {
  ColumnFiltersState,
  ColumnOrderState,
  Header,
  SortingState,
  Updater,
} from "@tanstack/react-table";
import clsx from "clsx";
import React from "react";
import type { DefaultRow } from "../../types";
import { getPrevFrozenWidthHeader } from "./lib";
import styles from "./table-header-cell.module.scss";

const RESIZE_HANDLE_WIDTH = 10;
const THRESHOLD = 2;

type Props<RowData extends DefaultRow> = {
  header: Header<RowData, unknown>;
  index: number;
  headers: Header<RowData, unknown>[];
  columnPosition: number;
  selectedPage: boolean;
  filterState?: ColumnFiltersState;
  sortState?: SortingState;
};

export const TableHeaderCell = React.memo(function TableHeaderCell<RowData extends DefaultRow>(
  props: Props<RowData>,
) {
  const headerContext = props.header.getContext();
  const headerClass = props.header.column.columnDef.headerClass;
  const headerClasses = headerClass.map((style) =>
    typeof style === "function"
      ? style(headerContext, props.header.column.columnDef.headerClassProps)
      : style,
  );
  const frozenPosition = props.header.column.getIsPinned();
  const prevFrozen = getPrevFrozenWidthHeader({
    frozenPosition,
    headers: props.headers,
    index: props.index,
  });
  const HeaderRender = props.header.column.columnDef.headerRender;
  const draggable = frozenPosition ? false : props.header.column.columnDef.enableDraggable;

  if (!HeaderRender) return null;

  return (
    <div
      role="columnheader"
      tabIndex={0}
      data-id="header-cell"
      data-column-id={headerContext.column.id}
      key={props.header.id}
      className={clsx(
        styles.headerCell,
        frozenPosition === "left" && styles.headerCell__frozen_left,
        frozenPosition === "right" && styles.headerCell__frozen_right,
        frozenPosition === "left" &&
          props.header.column.getIsLastColumn("left") &&
          styles.headerCell__frozen_left_last,
        frozenPosition === "right" &&
          props.header.column.getIsFirstColumn("right") &&
          styles.headerCell__frozen_right_first,
        headerClasses,
        "ksd-table-header-cell",
      )}
      style={{
        left: frozenPosition === "left" ? prevFrozen : undefined,
        right: frozenPosition === "right" ? prevFrozen : undefined,
        cursor: draggable ? "move" : "inherit",
        gridColumnStart: props.columnPosition,
      }}
      draggable={draggable}
      onDragOver={draggable ? (event) => event.preventDefault() : undefined}
      onDragStart={draggable ? handleDragStart : undefined}
      onDragEnd={draggable ? handleDragEnd : undefined}
      onDragEnter={draggable ? handleDragEnter : undefined}
      onDragLeave={draggable ? handleDragLeave : undefined}
      onDrop={
        draggable
          ? handleDropGetter(
              headerContext.table.getState().columnOrder,
              headerContext.table.setColumnOrder,
            )
          : undefined
      }
    >
      <HeaderRender
        context={headerContext}
        settings={props.header.column.columnDef.headerRenderProps}
      />

      {props.header.column.getCanResize() && (
        // eslint-disable-next-line jsx-a11y/no-static-element-interactions
        <div
          onMouseDown={props.header.getResizeHandler()}
          onTouchStart={props.header.getResizeHandler()}
          className={styles.headerResize}
          style={{
            width: RESIZE_HANDLE_WIDTH,
          }}
        />
      )}
    </div>
  );
}) as <RowData extends DefaultRow>(props: Props<RowData>) => React.JSX.Element;

function handleDragStart(event: React.DragEvent<HTMLElement>) {
  const { left, width } = event.currentTarget.getBoundingClientRect();
  const isOverResize = event.clientX >= left + width - RESIZE_HANDLE_WIDTH - THRESHOLD;

  if (isOverResize) {
    event.preventDefault();

    return;
  }

  if (event.dataTransfer) {
    const id = event.currentTarget.getAttribute("data-column-id");
    if (!id) return;

    event.dataTransfer.effectAllowed = "move";
    event.dataTransfer.setData("text", id);
    event.currentTarget.style.opacity = "var(--table-header-drag-opacity)";
  }
}

function handleDragEnd(event: React.DragEvent<HTMLElement>) {
  event.preventDefault();
  event.currentTarget.style.opacity = "1";
}

function handleDragEnter(event: React.DragEvent<HTMLElement>) {
  event.currentTarget.style.background = "var(--table-header-drag-bg)";
}

function handleDragLeave(event: React.DragEvent<HTMLElement>) {
  if (event.relatedTarget && !event.currentTarget.contains(event.relatedTarget as Node))
    event.currentTarget.style.background = "";
}

function handleDropGetter(
  columnOrderState: ColumnOrderState,
  setColumnOrderState: (updater: Updater<ColumnOrderState>) => void,
) {
  return function handleDrop(event: React.DragEvent<HTMLElement>) {
    event.preventDefault();
    event.currentTarget.style.background = "";
    const draggableId = event.dataTransfer?.getData?.("text");
    const droppableId = event.currentTarget.getAttribute("data-column-id");

    if (draggableId == undefined || droppableId == undefined || draggableId === droppableId) return;

    let draggableIndex: number = -1;
    let droppableIndex: number = -1;
    for (let i = 0; i <= columnOrderState.length; i++) {
      const id = columnOrderState[i];
      if (draggableId === id) {
        draggableIndex = i;
      }
      if (droppableId === id) {
        droppableIndex = i;
      }

      if (~draggableIndex && ~droppableIndex) break;
    }

    if (!~draggableIndex || !~droppableIndex) return;

    const order = [...columnOrderState];
    [order[+draggableIndex], order[+droppableIndex]] = [
      order[+droppableIndex],
      order[+draggableIndex],
    ];
    setColumnOrderState(order);
  };
}

// packages/vue-ui/src/ui/Table/components/Table/TableHeaderCell.vue
<script setup lang="ts" generic="RowData extends DefaultRow">
  import { type CSSProperties, computed, onMounted, onUnmounted, ref } from "vue";
  import { DND_EVENT_BUS, HEADER_CELL_DND_HANDLERS, getPrevFrozenWidthHeader } from "../../lib";
  import type { ColumnFiltersState, DefaultRow, HeaderInterface, SortingState } from "../../types";

  type Props = {
    header: HeaderInterface<RowData>;
    index: number;
    headers: HeaderInterface<RowData>[];
    columnPosition: number;
    selectedPage: boolean;
    filterState?: ColumnFiltersState;
    sortState?: SortingState;
  };
  const RESIZE_HANDLE_WIDTH = 10;
  const THRESHOLD = 2;
  const props = defineProps<Props>();
  const headerContext = computed(() => props.header.getContext());
  const id = computed(() => `header-column-${headerContext.value.column.id}`);
  const draggable = computed(() =>
    frozenPosition.value ? false : props.header.column.columnDef.enableDraggable,
  );
  const dragging = ref(false);
  const dragOver = ref(false);

  const frozenPosition = computed(() => props.header.column.getIsPinned());
  const prevFrozen = computed(() =>
    getPrevFrozenWidthHeader({
      frozenPosition: frozenPosition.value,
      headers: props.headers,
      index: props.index,
    }),
  );
  const HeaderRender = computed(() => props.header.column.columnDef.headerRender);

  const headerClasses = computed(() => ({
    "frozen-left": frozenPosition.value === "left",
    "frozen-right": frozenPosition.value === "right",
    "frozen-left-last":
      frozenPosition.value === "left" && props.header.column.getIsLastColumn("left"),
    "frozen-right-last":
      frozenPosition.value === "right" && props.header.column.getIsFirstColumn("right"),
    dragging,
    "drag-over": dragOver,
  }));
  const headerConfigClasses = computed(() =>
    props.header.column.columnDef.headerClass.map((className) =>
      className instanceof Function
        ? className(headerContext.value, props.header.column.columnDef.headerClassProps)
        : className,
    ),
  );
  const headerStyles = computed<CSSProperties>(() => ({
    left: frozenPosition.value === "left" ? prevFrozen.value : undefined,
    right: frozenPosition.value === "right" ? prevFrozen.value : undefined,
    cursor: draggable.value ? "move" : "inherit",
    gridColumnStart: props.columnPosition,
  }));

  function handleDragStart(event: DragEvent) {
    const { left, width } = (event.currentTarget as HTMLElement).getBoundingClientRect();
    const isOverResize = event.clientX >= left + width - RESIZE_HANDLE_WIDTH - THRESHOLD;

    if (isOverResize) {
      event.preventDefault();

      return;
    }

    HEADER_CELL_DND_HANDLERS.handleDragStart(event);
  }
  function handleDrop(event: DragEvent) {
    const { source, target } = HEADER_CELL_DND_HANDLERS.handleDrop(event) ?? {};

    if (source == undefined || target == undefined || source === target) {
      return;
    }

    const columnOrderState = headerContext.value.table.getState().columnOrder;
    let sourceIndex: number = -1;
    let targetIndex: number = -1;
    for (let i = 0; i <= columnOrderState.length; i++) {
      const id = columnOrderState[i];
      if (source === id) {
        sourceIndex = i;
      }
      if (target === id) {
        targetIndex = i;
      }

      if (~sourceIndex && ~targetIndex) break;
    }

    if (!~sourceIndex || !~targetIndex) return;

    const order = [...columnOrderState];
    [order[+sourceIndex], order[+targetIndex]] = [order[+targetIndex], order[+sourceIndex]];
    /** TODO: Проверить реактивность без мутации */
    headerContext.value.table.setColumnOrder(order);
  }

  onMounted(() => {
    DND_EVENT_BUS.subscribe(id.value, {
      enterDrag: function enterDrag() {
        dragOver.value = true;
      },
      leaveDrag: function leaveDrag() {
        dragOver.value = false;
      },
      startDrag: function startDrag() {
        dragging.value = true;
      },
      stopDrag: function stopDrag() {
        dragging.value = false;
      },
    });
  });

  onUnmounted(() => {
    DND_EVENT_BUS.unsubscribe(id.value);
  });
</script>

<template>
  <div
    role="columnheader"
    tabindex="0"
    :data-column-id="id"
    class="ksd-table__header-cell"
    :class="[headerClasses, headerConfigClasses]"
    :style="headerStyles"
    :draggable="draggable"
    @dragover="HEADER_CELL_DND_HANDLERS.handleDragOver"
    @dragstart="handleDragStart"
    @drop="handleDrop"
    @dragend="HEADER_CELL_DND_HANDLERS.handleDragEnd"
    @dragenter="HEADER_CELL_DND_HANDLERS.handleDragEnter"
    @dragleave="HEADER_CELL_DND_HANDLERS.handleDragLeave"
  >
    <component
      :is="HeaderRender"
      v-if="HeaderRender"
      :context="headerContext"
      :settings="headerContext.column.columnDef.headerRenderProps"
    />
    <div
      v-if="$props.header.column.getCanResize()"
      class="ksd-table__header-cell-resize"
      :style="{ width: RESIZE_HANDLE_WIDTH }"
      @mousedown="$props.header.getResizeHandler()"
      @touchstart="$props.header.getResizeHandler()"
    ></div>
  </div>
</template>

<style lang="scss">
  .ksd-table {
    &__header-cell {
      position: relative;
      display: block;

      &.frozen-left {
        position: sticky;
        z-index: 2;
      }
      &.frozen-right {
        position: sticky;
        z-index: 2;
      }
      &.frozen-left-last {
        box-shadow: var(--ksd-table-box-shadow-right);
      }
      &.frozen-right-first {
        box-shadow: var(--ksd-table-box-shadow-left);
        border-left: 1px solid var(--ksd-table-border);
      }
    }
    &__header-cell-resize {
      position: absolute;
      right: 0px;
      top: 0;
      z-index: 1;
      height: 100%;
      cursor: col-resize;
      user-select: none;
      touch-action: none;
    }
  }
</style>
