// packages/react-table/src/module/table/table-common.tsx
import type { VirtualItem, Virtualizer } from "@tanstack/react-virtual";
import clsx from "clsx";
import React from "react";
import type { HeaderInterface, RowInterface, TableInterface } from "../../types";
import styles from "./table-common.module.scss";
import { TableHeaderRow } from "./table-header-row";
import { TableRow } from "./table-row";

type TableContainerProps<RowData extends Record<string, unknown>> = {
  columnVirtualEnabled: boolean;
  rowVirtualEnabled: boolean;
  table: TableInterface<RowData>;
  frozenHeader: boolean;
  columnsVirtual: VirtualItem[];
  rowsVirtual: VirtualItem[];
  rows: RowInterface<RowData>[];
  rowVirtualizer: Virtualizer<HTMLDivElement, HTMLElement>;
  onClickRow:
    | ((row: RowInterface<RowData>, event: React.MouseEvent<HTMLElement>) => void)
    | undefined;
  onDoubleClickRow:
    | ((row: RowInterface<RowData>, event: React.MouseEvent<HTMLElement>) => void)
    | undefined;
  rowRender: ((row: RowInterface<RowData>) => React.JSX.Element | null | undefined) | undefined;
  rowClassName: ((row: RowInterface<RowData>) => string | undefined) | string | undefined;
  headerRowClassName:
    | ((header: HeaderInterface<RowData>) => string | undefined)
    | string
    | undefined;
  Empty: React.FC | undefined;
};

export function TableCommon<RowData extends Record<string, unknown>>(
  props: TableContainerProps<RowData>,
) {
  const leftHeadersGroup = props.table.getLeftHeaderGroups();
  const centerHeadersGroup = props.table.getCenterHeaderGroups();
  const rightHeadersGroup = props.table.getRightHeaderGroups();
  const visibleHeadersGroup = props.table.getHeaderGroups();
  const tableState = props.table.getState();

  const virtualColumnsIndexesKey = props.columnsVirtual.map((virtual) => virtual.index).join(";");
  const virtualColumns = React.useMemo(() => {
    return virtualColumnsIndexesKey.split(";");
  }, [virtualColumnsIndexesKey]);

  const visibleHeaders = visibleHeadersGroup?.[0]?.headers ?? [];

  return (
    <table
      className={styles.table}
      style={
        {
          width: props.columnVirtualEnabled ? props.table.getTotalSize() : "100%",
          "--table-template-columns": visibleHeaders
            .map((header) => `${header.getSize()}px`)
            .join(" "),
          "--table-total-width": props.table.getTotalSize(),
        } as React.CSSProperties
      }
      data-id="table"
    >
      <thead
        className={clsx(
          styles.header,
          (props.frozenHeader || props.frozenHeader == undefined) && styles.header__frozen,
        )}
        data-id="header"
      >
        {visibleHeadersGroup.map((headerGroup, index) => {
          const leftHeaders = leftHeadersGroup[index].headers;
          const centerHeaders = centerHeadersGroup[index].headers;
          const rightHeaders = rightHeadersGroup[index].headers;

          const selected = props.table.getIsAllPageRowsSelected();

          /** ROW HEADER */
          return (
            <TableHeaderRow<RowData>
              key={`${headerGroup.id}-header-row`}
              columnVirtualEnabled={props.columnVirtualEnabled}
              columnsVirtual={virtualColumns}
              headerGroup={headerGroup}
              centerHeaders={centerHeaders}
              leftHeaders={leftHeaders}
              rightHeaders={rightHeaders}
              headerRowClassName={props.headerRowClassName}
              page={tableState.pagination.pageIndex}
              selectedPage={selected}
              filterState={tableState.columnFilters}
              sortState={tableState.sorting}
            />
          );
        })}
      </thead>
      <tbody
        className={styles.body}
        style={{
          height:
            props.rowVirtualEnabled && props.rowsVirtual.length > 0
              ? `${props.rowVirtualizer.getTotalSize()}px`
              : undefined,
        }}
        data-id="body"
      >
        {props.rowVirtualEnabled &&
          props.rowsVirtual.map((virtualRow) => {
            const selected = props.rows[virtualRow.index]?.getIsSelected?.();
            const row = props.rows[virtualRow.index];
            const expanded = row.getIsExpanded();
            const CustomRow = props.rowRender?.(row);

            return (
              <TableRow<RowData>
                virtualRow={virtualRow}
                key={`${virtualRow.index}-row`}
                columnVirtualEnabled={props.columnVirtualEnabled}
                columnsVirtual={virtualColumns}
                rowClassName={props.rowClassName}
                rows={props.rows}
                onClickRow={props.onClickRow}
                onDoubleClickRow={props.onDoubleClickRow}
                rowVirtualizer={props.rowVirtualizer}
                row={null}
                selected={selected}
                expanded={expanded}
                CustomRow={CustomRow}
              />
            );
          })}
        {props.rowVirtualEnabled && props.rowsVirtual.length === 0 && props.Empty && (
          <props.Empty />
        )}
        {!props.rowVirtualEnabled &&
          props.rows.map((row) => {
            const selected = row.getIsSelected();
            const expanded = row.getIsExpanded();
            const CustomRow = props.rowRender?.(row);

            return (
              <TableRow<RowData>
                key={`${row.id}-row`}
                columnVirtualEnabled={props.columnVirtualEnabled}
                columnsVirtual={virtualColumns}
                row={row}
                rowClassName={props.rowClassName}
                onClickRow={props.onClickRow}
                onDoubleClickRow={props.onDoubleClickRow}
                rowVirtualizer={props.rowVirtualizer}
                rows={props.rows}
                virtualRow={null}
                selected={selected}
                expanded={expanded}
                CustomRow={CustomRow}
              />
            );
          })}
        {!props.rowVirtualEnabled && props.rows.length === 0 && props.Empty && <props.Empty />}
      </tbody>
    </table>
  );
}

// packages/vue-ui/src/ui/Table/components/Table/TableCommon.vue
<script setup lang="ts" generic="RowData extends DefaultRow">
  import type { VirtualItem, Virtualizer } from "@tanstack/vue-virtual";
  import { type CSSProperties, type Component, computed, onMounted, useTemplateRef } from "vue";
  import type {
    DefaultRow,
    HeaderGroupInterface,
    RowInterface,
    TableEmptyProps,
    TableInterface,
  } from "../../types";
  import TableHeaderRow from "./TableHeaderRow.vue";
  import TableRow from "./TableRow.vue";

  type Props = {
    rubberColumn: boolean;
    columnVirtualEnabled: boolean;
    rowVirtualEnabled: boolean;
    table: TableInterface<RowData>;
    frozenHeader: boolean;
    columnsVirtual: VirtualItem[];
    rowsVirtual: VirtualItem[];
    rows: RowInterface<RowData>[];
    rowVirtualizer: Virtualizer<HTMLDivElement, HTMLElement>;
    rowClassName: ((row: RowInterface<RowData>) => string | undefined) | string | undefined;
    headerRowClassName:
      | ((header: HeaderGroupInterface<RowData>) => string | undefined)
      | string
      | undefined;
    Row: ((row: RowInterface<RowData>) => Component | undefined) | undefined;
    Empty: Component<TableEmptyProps> | undefined;
    draggableRow: boolean;
  };
  type Emits = {
    dragRow: [sourceId: string, targetId: string];
    click: [row: RowInterface<RowData>, event: MouseEvent];
    dblclick: [row: RowInterface<RowData>, event: MouseEvent];
  };

  const props = defineProps<Props>();
  defineEmits<Emits>();
  const tableRef = useTemplateRef("table");

  const tableState = computed(() => props.table.getState());
  const leftHeadersGroup = computed(() => props.table.getLeftHeaderGroups());
  const rightHeadersGroup = computed(() => props.table.getRightHeaderGroups());
  const centerHeadersGroup = computed(() => props.table.getCenterHeaderGroups());
  const visibleHeadersGroup = computed(() => props.table.getHeaderGroups());

  const virtualColumnIndexesKey = computed(() =>
    props.columnsVirtual.length === 0
      ? null
      : props.columnsVirtual.map((virtual) => virtual.index).join(";"),
  );
  const virtualColumns = computed(() =>
    virtualColumnIndexesKey.value ? virtualColumnIndexesKey.value.split(";") : [],
  );
  const templateColumns = computed(
    () =>
      visibleHeadersGroup.value[0]?.headers?.map?.((header) => `${header.column.getSize()}px`) ??
      [],
  );
  const tableStyles = computed<CSSProperties>(() => ({
    "--table-template-columns": templateColumns.value.join(" "),
    "--table-total-width": props.table.getTotalSize(),
  }));
  const tableBodyStyles = computed<CSSProperties>(() => ({
    height:
      props.rowVirtualEnabled && props.rowsVirtual.length > 0
        ? `${props.rowVirtualizer.getTotalSize()}px`
        : undefined,
    "--table-body-height":
      props.rowVirtualEnabled && props.rowsVirtual.length > 0
        ? `${props.rowVirtualizer.getTotalSize()}px`
        : undefined,
  }));

  /** TODO: Rubber column logic */
  onMounted(() => {
    console.log(props.frozenHeader);
  });
</script>

<template>
  <div ref="table" role="table" class="ksd-table" :style="tableStyles">
    <div role="rowgroup" class="ksd-table__header" :class="{ frozen: $props.frozenHeader }">
      <TableHeaderRow
        v-for="(headerGroup, index) in visibleHeadersGroup"
        :key="headerGroup.id"
        :column-virtual-enabled="$props.columnVirtualEnabled"
        :columns-virtual="virtualColumns"
        :header-group="headerGroup"
        :left-headers="leftHeadersGroup[index].headers"
        :center-headers="centerHeadersGroup[index].headers"
        :right-headers="rightHeadersGroup[index].headers"
        :header-row-class-name="$props.headerRowClassName"
        :selected-page="$props.table.getIsAllPageRowsSelected()"
        :page="tableState.pagination.pageIndex"
        :filter-state="tableState.columnFilters"
        :sort-state="tableState.sorting"
        :height="undefined"
      />
    </div>
    <div role="rowgroup" class="ksd-table__body" :style="tableBodyStyles">
      <template v-if="$props.rowVirtualEnabled">
        <TableRow
          v-for="virtualRow in $props.rowsVirtual"
          :key="virtualRow.index"
          :column-virtual-enabled="$props.columnVirtualEnabled"
          :columns-virtual="virtualColumns"
          :rows="$props.rows"
          :row-virtualizer="$props.rowVirtualizer"
          :row="$props.rows[virtualRow.index]"
          :selected="$props.rows[virtualRow.index]?.getIsSelected?.()"
          :expanded="$props.rows[virtualRow.index]?.getIsExpanded()"
          :-row="$props.Row"
          :visible-cells="$props.rows[virtualRow.index]?.getVisibleCells?.() ?? []"
          :height="undefined"
          :draggable-row="$props.draggableRow"
          :row-class-name="$props.rowClassName"
          :virtual-row="virtualRow"
          @click="(row, event) => $emit('click', row, event)"
          @dblclick="(row, event) => $emit('dblclick', row, event)"
          @drag-row="
            (sid, tid) => {
              $emit('dragRow', sid, tid);
            }
          "
        />
      </template>
      <template v-if="!$props.rowVirtualEnabled">
        <TableRow
          v-for="row in $props.rows"
          :key="row.id"
          :column-virtual-enabled="$props.columnVirtualEnabled"
          :columns-virtual="virtualColumns"
          :rows="$props.rows"
          :row-virtualizer="$props.rowVirtualizer"
          :row="row"
          :selected="row?.getIsSelected?.()"
          :expanded="row?.getIsExpanded()"
          :-row="$props.Row"
          :visible-cells="row?.getVisibleCells?.() ?? []"
          :height="undefined"
          :draggable-row="$props.draggableRow"
          :row-class-name="$props.rowClassName"
          :virtual-row="null"
          @click="(row, event) => $emit('click', row, event)"
          @dblclick="(row, event) => $emit('dblclick', row, event)"
          @drag-row="(sid, tid) => $emit('dragRow', sid, tid)"
        />
      </template>
    </div>
  </div>
</template>

<style lang="scss">
  .ksd-table {
    border-spacing: 0px;
    table-layout: fixed;
    border-collapse: collapse;
    height: fit-content;
    width: 100%;
    display: flex;
    flex-direction: column;

    &__header {
      display: grid;
      display: flex;
      flex-direction: column;
      &.frozen {
        position: sticky;
        top: 0;
        z-index: 2;
      }
    }

    &__body {
      position: relative;
      background-color: var(--ksd-table-body-bg);
      display: flex;
      flex-direction: column;
      min-height: var(--table-body-height, 120px);
      flex: 1;
    }
  }
</style>
