// packages/vue-ui/src/ui/Table/components/Table/TableFooter.vue
<script setup lang="ts" generic="RowData extends DefaultRow">
  import { type Component, computed } from "vue";
  import PaginationComponent from "../../../Pagination.vue";
  import Text from "../../../Text.vue";
  import type { DefaultRow, TableInterface, TablePaginationProps } from "../../types";

  type Props = {
    withTotal: boolean | undefined;
    withPagination: boolean | undefined;
    table: TableInterface<RowData>;
    totalRows: number;
    pageSizes: number[] | undefined;
    Pagination?: Component<TablePaginationProps<RowData>>;
  };

  const props = defineProps<Props>();
  const paginationState = computed(() => props.table.getState().pagination);
  const pageSizes = computed(() => props.pageSizes ?? [10, 25, 50, 100, 150, 200]);
</script>

<template>
  <div v-if="$props.withTotal" class="ksd-table__total">
    <Text>Всего: {{ $props.totalRows }}</Text>
  </div>
  <PaginationComponent
    v-if="$props.withPagination && !$props.Pagination"
    :total-rows="$props.totalRows"
    :page-sizes="pageSizes"
    :model-value="paginationState.pageIndex"
    :page-size="paginationState.pageSize"
    placement="right"
    :class="'ksd-table__pagination'"
    @update:model-value="
      (value) => {
        props.table.setPageIndex(value);
      }
    "
    @update:page-size="
      (value) => {
        props.table.setPageSize(value);
      }
    "
  />
  <component
    :is="$props.withPagination && $props.Pagination"
    v-if="$props.Pagination"
    :table="$props.table"
    :page-index="paginationState.pageIndex"
    :page-size="paginationState.pageSize"
    :total-rows="$props.totalRows"
    :page-sizes="pageSizes"
  />
</template>

<style lang="scss">
  .ksd-table {
    &__total {
      display: flex;
      padding: 8px;
      border-bottom: 1px solid var(--ksd-table-border);
      border-left: 1px solid var(--ksd-table-border);
      border-right: 1px solid var(--ksd-table-border);
      background: var(--ksd-table-footer-bg);
    }
    &__pagination {
      margin-top: var(--ksd-margin);
    }
  }
</style>

// packages/react-table/src/module/table/table-footer.tsx
import { Pagination } from "@krainovsd/react-ui";
import React from "react";
import type { DefaultRow, TableInterface, TablePaginationProps } from "../../types";
import styles from "./table-footer.module.scss";

type TableFooterProps<RowData extends DefaultRow> = {
  Pagination: React.FC<TablePaginationProps<RowData>> | undefined;
  withPagination: boolean | undefined;
  withTotal: boolean | undefined;
  table: TableInterface<RowData>;
  pageIndex: number;
  pageSize: number;
  totalRows: number;
  pageSizes?: number[];
};

export const TableFooter = React.memo(function TableFooter<RowData extends DefaultRow>(
  props: TableFooterProps<RowData>,
) {
  const pageSizes = React.useMemo(() => {
    return props.pageSizes ?? [10, 25, 50, 100, 150, 200];
  }, [props.pageSizes]);

  return (
    <>
      {(props.withPagination || props.withTotal) && (
        <>
          <div className={styles.paginationContainer} data-id="footer">
            {props.withTotal && (
              <div className={styles.paginationTotal}>{`Всего: ${props.totalRows}`}</div>
            )}
            {props.withPagination && (
              <>
                {!props.Pagination && (
                  <Pagination
                    className={styles.pagination}
                    defaultCurrent={props.pageIndex + 1}
                    total={props.totalRows}
                    pageSize={props.pageSize}
                    onChange={(page, pageSize) => {
                      props.table.setPageIndex(page - 1);
                      props.table.setPageSize(pageSize);
                    }}
                    defaultPageSize={props.pageSize}
                    pageSizeOptions={pageSizes}
                    data-id="pagination"
                  />
                )}
                {props.Pagination && (
                  <props.Pagination
                    table={props.table}
                    pageIndex={props.pageIndex}
                    pageSize={props.pageSize}
                    pageSizes={pageSizes}
                    totalRows={props.totalRows}
                  />
                )}
              </>
            )}
          </div>
        </>
      )}
    </>
  );
}) as <RowData extends DefaultRow>(props: TableFooterProps<RowData>) => React.JSX.Element;
