// packages/vue-ui/src/ui/Table/components/FilterRenders/SelectFilterRender.vue
<script setup lang="ts" generic="RowData extends DefaultRow">
  import { isArray } from "@krainovsd/js-helpers";
  import type { SelectItem } from "../../../Select.vue";
  import Select from "../../../Select.vue";
  import type { DefaultRow, FilterRenderProps } from "../../types";

  export type SelectFilterRenderProps = {
    options: SelectItem<string | number>[];
    multiple?: boolean;
    search?: boolean;
    clear?: boolean;
    placeholder?: string;
  };

  defineProps<FilterRenderProps<RowData, SelectFilterRenderProps>>();
  const filterValue = defineModel<unknown>();
</script>

<template>
  <Select
    :options="$props.settings?.options ?? []"
    :multiple="$props.settings?.multiple"
    :search="$props.settings?.search"
    :clear="$props.settings?.clear"
    :placeholder="$props.settings?.placeholder"
    class="ksd-table__filter-select"
    :model-value="
      $props.settings?.multiple
        ? isArray(filterValue)
          ? (filterValue as string[] | number[])
          : undefined
        : (filterValue as string[] | number[])
    "
    @update:model-value="(value) => (filterValue = value)"
  />
</template>

<style lang="scss">
  .ksd-table__filter-select {
    min-width: 300px;
    max-width: 300px;
  }
</style>

// archive/react-table/src/components/filter-renders/select-filter-render.tsx
import { Select, type SelectItemInterface } from "@krainovsd/react-ui";
import type { DefaultRow, FilterRenderProps } from "../../types";

export type SelectFilterRenderProps = {
  options: SelectItemInterface[];
  multiple?: boolean;
};
export function SelectFilterRender<Row extends DefaultRow>(
  props: FilterRenderProps<Row, SelectFilterRenderProps>,
) {
  return (
    <Select
      mode={props.settings?.multiple ? "multiple" : undefined}
      variant="outlined"
      size="middle"
      style={{ width: "fit-content", minWidth: 200, maxWidth: 600 }}
      options={props.settings?.options}
      placeholder={"Выберите статус"}
    />
  );
}
