// packages/react-table/src/module/table/components/cell-renders/drag-cell-render.tsx
import { DragOutlined } from "@krainovsd/react-icons";
import clsx from "clsx";
import type { CellRenderProps, DefaultRow } from "../../../../types";
import { useVisibleCell } from "../../hooks";
import { CellRenderWrapper } from "../cell-render-wrapper";
import styles from "./drag-cell-render.module.scss";

export type DragCellRenderProps<Row extends DefaultRow> = {
  dragCondition?: (row: Row, index: number) => boolean;
};

export function DragCellRender<Row extends DefaultRow>(props: CellRenderProps<Row>) {
  const column = props.context.column.columnDef;
  const cellRenderProps = (column.cellRenderProps as DragCellRenderProps<Row>) ?? {};
  const draggable =
    typeof cellRenderProps.dragCondition === "function"
      ? cellRenderProps.dragCondition(props.context.row.original, props.context.row.index)
      : true;

  const { isVisible, level } = useVisibleCell(props.context);

  if (!isVisible) return;

  return (
    <CellRenderWrapper
      column={column}
      context={props.context}
      level={level}
      className={clsx(
        draggable && "ksd-table-drag-handle",
        draggable && styles.drag,
        !draggable && styles.forbidden,
      )}
      onClick={(event) => event.stopPropagation()}
      onDoubleClick={(event) => event.stopPropagation()}
    >
      <DragOutlined size={16} />
    </CellRenderWrapper>
  );
}

// packages/vue-ui/src/ui/Table/components/CellRenders/DragCellRender.vue
<script setup lang="ts" generic="RowData extends DefaultRow">
  import { VHolderOutlined } from "@krainovsd/vue-icons";
  import { computed } from "vue";
  import Button from "../../../Button.vue";
  import { checkCellVisible } from "../../lib/check-cell-visible";
  import type { CellRenderProps, DefaultRow } from "../../types";

  export type DragCellRenderProps<Row extends DefaultRow> = {
    dragCondition?: (row: Row, index: number) => boolean;
  };

  const props = defineProps<CellRenderProps<RowData, DragCellRenderProps<RowData>>>();
  const draggable = computed(() =>
    props.settings?.dragCondition instanceof Function
      ? props.settings.dragCondition(props.context.row.original, props.context.row.index)
      : true,
  );
  const visible = computed(() => checkCellVisible(props.context));
</script>

<template>
  <div
    v-if="visible"
    class="ksd-table__cell-drag"
    @click="(event) => event.stopPropagation()"
    @dblclick="(event) => event.stopPropagation()"
  >
    <Button
      type="text"
      size="small"
      class="ksd-table-row-drag-handle"
      :class="{ drag: draggable, forbidden: !draggable }"
    >
      <VHolderOutlined />
    </Button>
  </div>
</template>

<style lang="scss">
  div.ksd-table__cell-drag {
    & > svg {
      font-size: var(--ksd-font-size-lg);
    }
  }

  button.ksd-table-row-drag-handle {
    &.drag {
      cursor: move;
    }
    &.forbidden {
      cursor: not-allowed;
    }
  }
</style>
