// packages/vue-ui/src/ui/Table/components/FilterRenders/DateRangeFilterRender.vue
<script setup lang="ts" generic="RowData extends DefaultRow">
  import type { DefaultRow, FilterRenderProps } from "../../types";

  export type DateRangeFilterRenderProps = {
    format: string;
  };

  defineProps<FilterRenderProps<RowData, DateRangeFilterRenderProps>>();
</script>

<template>
  <div>component</div>
</template>

<style lang="scss" module></style>

// packages/react-table/src/components/filter-renders/date-range-filter-render.tsx
import { DateRangePicker } from "@krainovsd/react-ui";
import type { DefaultRow, FilterRenderProps } from "../../types";

export type DateRangeFilterRenderProps = {
  format: string;
};
export function DateRangeFilterRender<Row extends DefaultRow>(
  props: FilterRenderProps<Row, DateRangeFilterRenderProps>,
) {
  return <DateRangePicker format={props.settings?.format} />;
}
