// packages/react-table/src/module/table/components/header-renders/select-header-render.tsx
import { CheckBox } from "@krainovsd/react-ui";
import type { DefaultRow, HeaderRenderProps } from "../../../../types";

type CheckProps = (props: {
  checked: boolean;
  onChange: React.ChangeEventHandler<HTMLInputElement>;
}) => React.ReactNode;
export type SelectHeaderRenderProps = {
  Check?: CheckProps;
};
export function SelectHeaderRender<RowData extends DefaultRow>(props: HeaderRenderProps<RowData>) {
  const headerRenderProps = props.context.column.columnDef.headerRenderProps as
    | SelectHeaderRenderProps
    | undefined;
  const Check = headerRenderProps?.Check ?? CheckBox;
  const checked = props.context.table.getIsAllPageRowsSelected();

  return (
    <div className="ksd-table-header-cell-container">
      <Check
        checked={checked}
        onChange={() => {
          props.context.table.toggleAllPageRowsSelected();
        }}
      />
    </div>
  );
}

// packages/vue-ui/src/ui/Table/components/HeaderRenders/SelectHeaderRender.vue
<script setup lang="ts" generic="RowData extends DefaultRow">
  import type { DefaultRow, HeaderRenderProps } from "../../types";

  export type SelectHeaderRenderProps = {
    Check?: (props: {
      checked: boolean;
      onChange: React.ChangeEventHandler<HTMLInputElement>;
    }) => React.ReactNode;
  };

  defineProps<HeaderRenderProps<RowData, SelectHeaderRenderProps>>();
</script>

<template>
  <div>component</div>
</template>

<style lang="scss" module></style>
