// packages/vue-ui/src/ui/Table/components/Table/TableRow.vue
<script setup lang="ts" generic="RowData extends DefaultRow">
  import type { VirtualItem, Virtualizer } from "@tanstack/vue-virtual";
  import {
    type CSSProperties,
    type Component,
    type ComponentPublicInstance,
    computed,
    onMounted,
    onUnmounted,
    ref,
  } from "vue";
  import { DND_EVENT_BUS, ROW_DND_HANDLERS } from "../../lib";
  import type { CellInterface, DefaultRow, RowInterface } from "../../types";
  import TableCell from "./TableCell.vue";

  type Props = {
    rows: RowInterface<RowData>[];
    selected: boolean;
    row: RowInterface<RowData>;
    columnsVirtual: string[];
    virtualRow: VirtualItem | null;
    rowVirtualizer: Virtualizer<HTMLDivElement, HTMLElement>;
    rowClassName: ((row: RowInterface<RowData>) => string | undefined) | string | undefined;
    columnVirtualEnabled: boolean;
    expanded: boolean;
    Row: ((row: RowInterface<RowData>) => Component | undefined) | undefined;
    visibleCells: CellInterface<RowData>[];
    height: number | undefined;
    draggableRow: boolean;
  };
  type Emits = {
    dragRow: [
      sourceIndex: number,
      targetIndex: number,
      sourceId: number | string,
      targetId: number | string,
    ];
    click: [row: RowInterface<RowData>, event: MouseEvent];
    dblclick: [row: RowInterface<RowData>, event: MouseEvent];
  };

  const props = defineProps<Props>();
  const emit = defineEmits<Emits>();

  const rowIndex = computed(() => (props.virtualRow ? props.virtualRow.index : props.row.index));
  const id = computed(() => `row-${rowIndex.value}`);
  const dragging = ref(false);
  const dragOver = ref(false);
  // eslint-disable-next-line new-cap
  const CustomRow = computed(() => props.Row?.(props.row));
  const leftVisibleCells = computed(() => props.row.getLeftVisibleCells());
  const centerVisibleCells = computed(() => props.row.getCenterVisibleCells());
  const rightVisibleCells = computed(() => props.row.getRightVisibleCells());

  const rowClasses = computed(() => ({
    selected: props.selected,
    virtual: props.virtualRow,
    dragging: dragging.value,
    "drag-over": dragOver.value,
  }));
  const rowConfigClasses = computed(() =>
    props.rowClassName instanceof Function ? props.rowClassName(props.row) : props.rowClassName,
  );
  const rowStyles = computed<CSSProperties>(() => ({
    transform: props.virtualRow ? `translateY(${props.virtualRow.start}px)` : undefined,
    minHeight: props.height,
    maxHeight: props.height,
  }));
  const rowRef = computed(() => {
    return props.virtualRow
      ? (node: Element | ComponentPublicInstance | null) =>
          node instanceof HTMLElement && props.rowVirtualizer.measureElement(node)
      : undefined;
  });

  function handleDragStart(event: DragEvent) {
    const target = document.elementFromPoint(event.clientX, event.clientY) as HTMLElement | null;

    const isDragHandle =
      target?.classList?.contains?.("ksd-table-drag-handle") ||
      target?.closest?.(".ksd-table-drag-handle");
    if (!target || !isDragHandle) {
      event.stopPropagation();
      event.preventDefault();

      return;
    }

    ROW_DND_HANDLERS.handleDragStart(event);
  }

  function handleDrop(event: DragEvent) {
    const { source, target } = ROW_DND_HANDLERS.handleDrop(event);
    if (source == undefined || target == undefined || source === target) return;

    const sourceIndex = +source.replace("row-", "");
    const targetIndex = +target.replace("row-", "");

    if (Number.isNaN(sourceIndex) || Number.isNaN(targetIndex)) {
      return;
    }

    const sourceId = props.rows[sourceIndex].id;
    const targetId = props.rows[targetIndex].id;

    emit("dragRow", sourceIndex, targetIndex, sourceId, targetId);
  }

  function onKeyDown(event: KeyboardEvent) {
    const target = event.target as HTMLDivElement;
    const currentTarget = event.currentTarget as HTMLDivElement;

    if ((event.key === " " || event.key === "Enter") && target === currentTarget) {
      event.preventDefault();
      currentTarget.click();
    }
    if (event.key === "ArrowUp" && currentTarget.previousElementSibling instanceof HTMLDivElement) {
      currentTarget.previousElementSibling.focus();
      event.preventDefault();
    }
    if (event.key === "ArrowDown" && currentTarget.nextElementSibling instanceof HTMLDivElement) {
      currentTarget.nextElementSibling.focus();
      event.preventDefault();
    }
  }

  onMounted(() => {
    DND_EVENT_BUS.subscribe(id.value, {
      enterDrag: function enterDrag() {
        dragOver.value = true;
      },
      leaveDrag: function leaveDrag() {
        dragOver.value = false;
      },
      startDrag: function startDrag() {
        dragging.value = true;
      },
      stopDrag: function stopDrag() {
        dragging.value = false;
      },
    });
  });

  onUnmounted(() => {
    DND_EVENT_BUS.unsubscribe(id.value);
  });
</script>

<template>
  <div
    :ref="rowRef"
    role="row"
    tabindex="0"
    class="ksd-table__row"
    :class="[rowClasses, rowConfigClasses]"
    :style="rowStyles"
    :data-index="rowIndex"
    :data-row-id="id"
    :draggable="$props.draggableRow"
    @click="(event) => $emit('click', $props.row, event)"
    @dblclick="(event) => $emit('dblclick', $props.row, event)"
    @keydown="onKeyDown"
    @dragstart="handleDragStart"
    @drop="handleDrop"
    @dragend="ROW_DND_HANDLERS.handleDragEnd"
    @dragover="ROW_DND_HANDLERS.handleDragOver"
    @dragenter="ROW_DND_HANDLERS.handleDragEnter"
    @dragleave="ROW_DND_HANDLERS.handleDragLeave"
  >
    <template v-if="props.columnVirtualEnabled && !CustomRow">
      <TableCell
        v-for="(cell, index) in leftVisibleCells"
        :key="cell.column.columnDef.id"
        :cell="cell"
        :cells="leftVisibleCells"
        :column-position="index + 1"
        :index="index"
        :selected="$props.selected"
        :expanded="$props.expanded"
      />
      <TableCell
        v-for="index in props.columnsVirtual"
        :key="centerVisibleCells[+index].column.columnDef.id"
        :cell="centerVisibleCells[+index]"
        :cells="centerVisibleCells"
        :column-position="leftVisibleCells.length + +index + 1"
        :index="+index"
        :selected="$props.selected"
        :expanded="$props.expanded"
      />
      <TableCell
        v-for="(cell, index) in rightVisibleCells"
        :key="cell.column.columnDef.id"
        :cell="cell"
        :cells="rightVisibleCells"
        :column-position="leftVisibleCells.length + centerVisibleCells.length + index + 1"
        :index="index"
        :selected="$props.selected"
        :expanded="$props.expanded"
      />
    </template>
    <template v-if="!props.columnVirtualEnabled && !CustomRow">
      <TableCell
        v-for="(cell, index) in $props.visibleCells"
        :key="cell.column.columnDef.id"
        :cell="cell"
        :cells="$props.visibleCells"
        :column-position="index + 1"
        :index="index"
        :selected="$props.selected"
        :expanded="$props.expanded"
      />
    </template>
    <component :is="CustomRow" v-if="CustomRow" />
  </div>
</template>

<style lang="scss">
  .ksd-table {
    &__row {
      display: grid;
      background-color: var(--ksd-table-row-bg);
      position: relative;
      width: calc(var(--table-total-width) * 1px);
      grid-template-columns: var(--table-template-columns);

      &:hover {
        background-color: var(--ksd-table-row-hover-bg);
      }
      &:focus-visible {
        background-color: var(--ksd-table-row-hover-bg);
        outline: none;
      }

      &.selected {
        background-color: var(--ksd-table-selected-row-bg);

        &:hover {
          background-color: var(--ksd-table-selected-row-hover-bg);
        }
        &:focus-visible {
          background-color: var(--ksd-table-selected-row-hover-bg);
          outline: none;
        }
      }
      &.virtual {
        position: absolute;
      }
      &.dragging {
        opacity: var(--ksd-table-row-drag-opacity);
      }
      &.drag-over {
        background-color: var(--ksd-table-row-drag-bg);
      }
    }
  }
</style>

// archive/react-table/src/components/table/table-row.tsx
import type { Cell } from "@tanstack/react-table";
import type { VirtualItem, Virtualizer } from "@tanstack/react-virtual";
import clsx from "clsx";
import React from "react";
import type { DefaultRow, DragRowHandler, RowInterface } from "../../types";
import { TableCell } from "./table-cell";
import styles from "./table-row.module.scss";

type Props<RowData extends DefaultRow> = {
  rows: RowInterface<RowData>[];
  selected: boolean;
  row: RowInterface<RowData> | null;
  columnsVirtual: string[];
  virtualRow: VirtualItem | null;
  rowVirtualizer: Virtualizer<HTMLDivElement, HTMLElement>;
  rowClassName: ((row: RowInterface<RowData>) => string | undefined) | string | undefined;
  onClickRow:
    | ((row: RowInterface<RowData>, event: React.MouseEvent<HTMLElement>) => void)
    | undefined;
  onDoubleClickRow:
    | ((row: RowInterface<RowData>, event: React.MouseEvent<HTMLElement>) => void)
    | undefined;
  columnVirtualEnabled: boolean;
  expanded: boolean;
  CustomRow: React.JSX.Element | undefined | null;
  visibleCells: Cell<RowData, unknown>[];
  height: number | undefined;
  draggableRow: boolean;
  onDraggableRow: DragRowHandler | undefined;
};

export const TableRow = React.memo(function TableRow<RowData extends DefaultRow>(
  props: Props<RowData>,
) {
  const row = props.virtualRow ? props.rows[props.virtualRow.index] : props.row;
  const draggable = Boolean(props.draggableRow && props.onDraggableRow);

  if (!row) return;
  const leftVisibleCells = row.getLeftVisibleCells();
  const centerVisibleCells = row.getCenterVisibleCells();
  const rightVisibleCells = row.getRightVisibleCells();

  function onKeyDown(event: React.KeyboardEvent<HTMLDivElement>) {
    if ((event.key === " " || event.key === "Enter") && event.target === event.currentTarget) {
      event.preventDefault();
      event.currentTarget.click();
    }
    if (
      event.key === "ArrowUp" &&
      event.currentTarget.previousElementSibling instanceof HTMLDivElement
    ) {
      event.currentTarget.previousElementSibling.focus();
      event.preventDefault();
    }
    if (
      event.key === "ArrowDown" &&
      event.currentTarget.nextElementSibling instanceof HTMLDivElement
    ) {
      event.currentTarget.nextElementSibling.focus();
      event.preventDefault();
    }
  }

  /** ROW */
  return (
    <div
      data-id="row"
      role="row"
      tabIndex={0}
      key={row.id}
      className={clsx(
        styles.row,
        props.selected && styles.row__selected,
        props.virtualRow && styles.row__virtual,
        typeof props.rowClassName === "function" ? props.rowClassName(row) : props.rowClassName,
        "ksd-table-row",
      )}
      data-index={props.virtualRow ? props.virtualRow.index : row.index}
      ref={props.virtualRow ? (node) => props.rowVirtualizer.measureElement(node) : undefined}
      style={{
        transform: props.virtualRow ? `translateY(${props.virtualRow.start}px)` : undefined,
        minHeight: props.height,
        maxHeight: props.height,
      }}
      onClick={(event) => {
        props.onClickRow?.(row, event);
      }}
      onDoubleClick={(event) => {
        props.onDoubleClickRow?.(row, event);
      }}
      onKeyDown={onKeyDown}
      draggable={draggable}
      onDragOver={draggable ? (event) => event.preventDefault() : undefined}
      onDragStart={draggable ? handleDragStart : undefined}
      onDragEnd={draggable ? handleDragEnd : undefined}
      onDragEnter={draggable ? handleDragEnter : undefined}
      onDragLeave={draggable ? handleDragLeave : undefined}
      onDrop={draggable ? handleDropGetter(props.rows, props.onDraggableRow) : undefined}
    >
      <>
        {props.columnVirtualEnabled && !props.CustomRow && (
          <>
            {leftVisibleCells.map((cell, index, cells) => {
              /** LEFT CELL */

              return (
                <TableCell
                  key={cell.column.columnDef.id}
                  cell={cell}
                  index={index}
                  cells={cells}
                  columnPosition={index + 1}
                  selected={props.selected}
                  expanded={props.expanded}
                />
              );
            })}
            {props.columnsVirtual.map((index) => {
              /** CENTER CELL */

              const cell = centerVisibleCells[+index];

              return (
                <TableCell
                  key={cell.column.columnDef.id}
                  cell={cell}
                  index={+index}
                  cells={centerVisibleCells}
                  selected={props.selected}
                  columnPosition={leftVisibleCells.length + +index + 1}
                  expanded={props.expanded}
                />
              );
            })}
            {rightVisibleCells.map((cell, index, cells) => {
              /** RIGHT CELL */

              return (
                <TableCell
                  key={cell.column.columnDef.id}
                  cell={cell}
                  index={index}
                  cells={cells}
                  columnPosition={leftVisibleCells.length + centerVisibleCells.length + index + 1}
                  selected={props.selected}
                  expanded={props.expanded}
                />
              );
            })}
          </>
        )}
        {!props.columnVirtualEnabled &&
          !props.CustomRow &&
          props.visibleCells.map((cell, index, cells) => {
            /** CELL */

            return (
              <TableCell
                key={cell.column.columnDef.id}
                cell={cell}
                index={index}
                cells={cells}
                columnPosition={index + 1}
                selected={props.selected}
                expanded={props.expanded}
              />
            );
          })}
        {props.CustomRow && props.CustomRow}
      </>
    </div>
  );
}) as <RowData extends DefaultRow>(props: Props<RowData>) => React.JSX.Element;

function isDragHandle(element: HTMLElement) {
  return (
    element.classList.contains("ksd-table-drag-handle") || element.closest(".ksd-table-drag-handle")
  );
}

function handleDragStart(event: React.DragEvent<HTMLElement>) {
  const target = document.elementFromPoint(event.clientX, event.clientY) as HTMLElement | null;

  if (!target || !isDragHandle(target)) {
    event.stopPropagation();
    event.preventDefault();

    return;
  }

  if (event.dataTransfer) {
    const index = event.currentTarget.getAttribute("data-index");
    if (!index) return;

    event.dataTransfer.effectAllowed = "move";
    event.dataTransfer.setData("text", index);
    event.currentTarget.style.opacity = "var(--table-header-drag-opacity)";
  }
}
function handleDragEnd(event: React.DragEvent<HTMLElement>) {
  event.preventDefault();
  event.currentTarget.style.opacity = "1";
}
function handleDragEnter(event: React.DragEvent<HTMLElement>) {
  event.currentTarget.style.background = "var(--table-row-drag-bg)";
}
function handleDragLeave(event: React.DragEvent<HTMLElement>) {
  if (event.relatedTarget && !event.currentTarget.contains(event.relatedTarget as Node))
    event.currentTarget.style.background = "";
}
function handleDropGetter<RowData extends DefaultRow>(
  rows: RowInterface<RowData>[],
  onDraggableRow: DragRowHandler | undefined,
) {
  return function handleDrop(event: React.DragEvent<HTMLElement>) {
    event.preventDefault();
    event.currentTarget.style.background = "";

    const sourceIndex = +event.dataTransfer?.getData?.("text");
    let targetIndex: number | string | null = event.currentTarget.getAttribute("data-index");
    if (targetIndex != undefined) targetIndex = +targetIndex;

    if (
      Number.isNaN(sourceIndex) ||
      targetIndex == undefined ||
      Number.isNaN(targetIndex) ||
      sourceIndex === targetIndex
    )
      return;

    const sourceId = rows[sourceIndex].id;
    const targetId = rows[targetIndex].id;

    onDraggableRow?.(sourceIndex, targetIndex, sourceId, targetId);
  };
}
