// packages/vue-ui/src/ui/Table/components/HeaderRenders/DefaultHeaderRender.vue
<script setup lang="ts" generic="RowData extends DefaultRow">
  import { computed } from "vue";
  import type { DefaultRow, HeaderRenderProps } from "../../types";

  const props = defineProps<HeaderRenderProps<RowData, unknown>>();
  const SortRender = computed(() => props.context.column.columnDef.sortRender);
  const canSort = computed(() => props.context.column.getCanSort());
</script>

<template>
  <div>
    <span class="ksd-table__header-cell-default-text">{{
      props.context.column.columnDef.name
    }}</span>
    <component :is="SortRender" v-if="SortRender && canSort" :context="$props.context" />
  </div>
</template>

<style lang="scss">
  span.ksd-table__header-cell-default-text {
    display: block;
    max-width: 100%;
    overflow: hidden;
    text-overflow: ellipsis;
  }
</style>

// packages/react-table/src/components/header-renders/default-header-render.tsx
import type { DefaultRow, HeaderRenderProps } from "../../types";
import styles from "./default-header-render.module.scss";

export function DefaultHeaderRender<RowData extends DefaultRow>(props: HeaderRenderProps<RowData>) {
  const SortRender = props.context.column.columnDef.sortRender;
  const canSort = props.context.column.getCanSort();

  return (
    <div className="ksd-table-header-cell-container">
      <span className={styles.text}>{props.context.column.columnDef.name}</span>
      {canSort && SortRender && (
        <SortRender
          context={props.context}
          settings={props.context.column.columnDef.sortRenderProps}
        />
      )}
    </div>
  );
}
