// packages/react-table/src/components/filter-renders/date-filter-render.tsx
import { DatePicker } from "antd";
import type { DefaultRow, FilterRenderProps } from "../../types";

export type DateFilterRenderProps = {
  format: string;
};
export function DateFilterRender<Row extends DefaultRow>(
  props: FilterRenderProps<Row, DateFilterRenderProps>,
) {
  return <DatePicker format={props.settings?.format} />;
}

// packages/vue-ui/src/ui/Table/components/FilterRenders/DateFilterRender.vue
<script setup lang="ts" generic="RowData extends DefaultRow">
  import type { DefaultRow, FilterRenderProps } from "../../types";

  export type DateFilterRenderProps = {
    format: string;
  };

  defineProps<FilterRenderProps<RowData, DateFilterRenderProps>>();
</script>

<template>
  <div>component</div>
</template>

<style lang="scss" module></style>
